name: Release

on:
  release:
    types:
      - released

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Authenticate with GitHub NPM registry
        run: |
          npm config set @rugaard:registry https://npm.pkg.github.com/rugaard && \
          npm config set //npm.pkg.github.com/:_authToken "${{ secrets.GITHUB_TOKEN }}"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set release version
        run: |
          npm config set commit-hooks false
          npm config set git-tag-version false
          npm version "${GITHUB_REF#refs/tags/}"
      - name: Release
        run: npm publish --access public
